### PR TITLE
Small Update to readme.md

### PR DESCRIPTION
**Pull request by StealthHydra179**

### CODE REVIEW

**Comment by torralbaa** [comment]
Fixed capitalization, I don't see any problem in merging this.

@RealCreepi?

**Comment by iiisak** [comment]
Thanks I will merge this later today!

**Comment by StealthHydra179** [comment]
> Fixed capitalization, I don't see any problem in merging this.
> 
> @RealCreepi?

Errr uhhh eeeeeee GitHub has to be capitalized? :(

**Comment by torralbaa** [comment]
> > Fixed capitalization, I don't see any problem in merging this.
> > @RealCreepi?
> 
> Errr uhhh eeeeeee GitHub has to be capitalized? :(

Uhm, yes?

**Comment by torralbaa** [comment]
> Thanks I will merge this later today!

I can do it if you want.

**Comment by StealthHydra179** [comment]
> > > Fixed capitalization, I don't see any problem in merging this.
> > > @RealCreepi?
> > 
> > 
> > Errr uhhh eeeeeee GitHub has to be capitalized? :(
> 
> Uhm, yes?

_sigh_ fine.

**Comment by iiisak** [comment]
> > Thanks I will merge this later today!
> 
> I can do it if you want.

I don't want to forget to `git pull` so yeah

**Pull request merged**
